### PR TITLE
Miniscript enroll

### PR DESCRIPTION
**Pull request by edouardparis**
Hello, thank you very much for the library.

this PR adds two feature:
-  the new miniscript enroll that is used in [Edge v6.2.1](https://coldcard.com/docs/upgrade/#edge-version-621x-development-purposes)
- A public exposure of some components to make it compatible with external Hidapi without taking ownership of it, [example](https://github.com/wizardsardine/async-hwi/pull/57/files#diff-c1f8f7498da827a634bddc8a7559198bc99b296e9d9e8b91a70b503662995b8c)

### CODE REVIEW

**Comment by alfred-hodler** [comment]
Thank you for this improvement.

Could you please squash everything into a single commit, create a commit message in the style of previous commit messages and sign the commit? For example:

```
    Internal improvements
    
    * libsecp256k1 has been removed in favor of a native implementation (k256)
    
    * Improved device detection capabilities
    
    * CLI removes the remote connect feature
```
Furthermore, is there a summary of differences in HidApi between `2.4.1` and `1.3.3`?

**Comment by edouardparis** [comment]
Updated and signed the commit.

[Here](https://gist.github.com/edouardparis/9ab3be742b2ec766f681a672f60dcc79) a summary off the differences between Hidapi  `2.4.1` and `1.3.3`.

The version increase of the library is to satisfy common dependency tree between multiple hardware wallet client libraries.

**Comment by alfred-hodler** [comment]
Merged and bumped semver to `0.9.0`. Will publish on crates.io shortly. Thanks again.

**Comment by edouardparis** [comment]
Thank you very much

**Pull request merged**
